// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALIDRKM4qewcASv4GzsxTzkmT8em5H5VY',
    appId: '1:750059618575:web:e4b11cc31e8a234a38be7a',
    messagingSenderId: '750059618575',
    projectId: 'demp-iti',
    authDomain: 'demp-iti.firebaseapp.com',
    storageBucket: 'demp-iti.firebasestorage.app',
    measurementId: 'G-2NRV6E9FWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3GuTFHciwly9Jr9hRtvGBZCpHYNZGo48',
    appId: '1:750059618575:android:94c6723387ff86fb38be7a',
    messagingSenderId: '750059618575',
    projectId: 'demp-iti',
    storageBucket: 'demp-iti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUOlWxm8cIeNlR2P4skIjXQ6DAVSEW9Oc',
    appId: '1:750059618575:ios:e70a49db276fb03e38be7a',
    messagingSenderId: '750059618575',
    projectId: 'demp-iti',
    storageBucket: 'demp-iti.firebasestorage.app',
    iosBundleId: 'com.example.demoIti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUOlWxm8cIeNlR2P4skIjXQ6DAVSEW9Oc',
    appId: '1:750059618575:ios:e70a49db276fb03e38be7a',
    messagingSenderId: '750059618575',
    projectId: 'demp-iti',
    storageBucket: 'demp-iti.firebasestorage.app',
    iosBundleId: 'com.example.demoIti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALIDRKM4qewcASv4GzsxTzkmT8em5H5VY',
    appId: '1:750059618575:web:3eed90b1940b169838be7a',
    messagingSenderId: '750059618575',
    projectId: 'demp-iti',
    authDomain: 'demp-iti.firebaseapp.com',
    storageBucket: 'demp-iti.firebasestorage.app',
    measurementId: 'G-CL4XQ3HLT9',
  );
}
